services:
  - type: web
    name: master-ai-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false

  - type: web
    name: master-ai-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://qx-mashaallha.onrender.com
